# Generated by Django 3.0.4 on 2020-03-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='User',
        ),
    ]
